### ISSUE TITLE
Mage registry key "_singleton/Yireo_DisableLog_Observer_Feed" already exists

### ISSUE THREAD

**Issue by cscd98** [yireo/Yireo_DisableLog#3]
Logging into admin

```
a:5:{i:0;s:76:"Mage registry key "_singleton/Yireo_DisableLog_Observer_Feed" already exists";i:1;s:1773:"#0
```

**Comment by jissereitsma** [comment]
Is this really an issue with this extension? Because Magento StackExchange is full of this type of errors, and they normally indicate a wrong install procedure: Wipe out cache, logout from admin session, login again.

**Comment by rikwillems** [comment]
I have the same after upgrade from a15f8bf611484036cb0db66396cfbca7199f8d29 and can't get it away. Specific to the System > Configuration area, the rest is ok.

**Comment by jissereitsma** [comment]
Are there multiple extensions of Yireo installed? If so, which?

**Comment by rikwillems** [comment]
I have Yireo_CheckoutTester as well. If I remove it I have the same issue.

**Comment by jissereitsma** [comment]
In almost all of the cases where I've encountered an error like `Mage registry key _singleton/X already exists` in Magento, this was actually due to a wrong admin session (wipe cookies) or outdated cache (wipe cache). I've just checked for this in three environments with the latest version of the Yireo DisableLog extension installed, and am not encountering this issue anywhere else. Since this error is actually generic in Magento, I'm confident that it is not related to the extension, but to something in the cache of your Magento. I can't duplicate the issue anyway, so can't do much more anyway.

**Comment by aurmil** [comment]
have it too on a system not displaying errors
when displaying errors is ON, I get https://github.com/yireo/Yireo_DisableLog/issues/4

edit: not from display error but from MAGE_IS_DEVELOPER_MODE

**Comment by jissereitsma** [comment]
It could be that this is related to #4 indeed: There is a file missing from the GitHub repository, which is not missing in the patch-files and MagentoConnect packages on our site. Could it be that this extension is installed by all of you via `composer`? Because if you are not using composer, the recommended way is to use the ready-made packages on our site.

**Comment by aurmil** [comment]
on my side, install was made through modman so github
